repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@^2.1.0
                - '@trivago/prettier-plugin-sort-imports@^4.3.0'
                - '@vue/compiler-sfc@^3.3.9'
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.54.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@^8.54.0
                - '@typescript-eslint/eslint-plugin@^6.12.0'
                - '@typescript-eslint/parser@^6.12.0'
