<script lang="ts">
import {type IVerilogWorkerOptions, type ProjectTarget, getIVerilogWorkerOptions} from 'edacation';
import {defineComponent} from 'vue';

import type {Project} from '../../../exchange';
import {syncedState as projectState} from '../../project';
import {state as globalState} from '../state';

import EDATargetValueList from './EDATargetValueList.vue';
import EDATestbenchSelector from './EDATestbenchSelector.vue';

type PotentialError<WorkerOptions> = {status: 'ok'; res: WorkerOptions} | {status: 'error'; err: Error};

export default defineComponent({
    components: {
        EDATargetValueList,
        EDATestbenchSelector
    },
    props: {
        targetIndex: {
            type: Number
        }
    },
    data() {
        return {
            state: globalState,
            projectState
        };
    },
    computed: {
        target(): ProjectTarget | undefined {
            if (this.targetIndex === undefined) {
                return undefined;
            }
            return this.projectState.project?.getTargets()[this.targetIndex];
        },
        generated(): PotentialError<IVerilogWorkerOptions | null> {
            if (!this.target || !this.projectState.project) return {status: 'ok', res: null};

            try {
                const options = getIVerilogWorkerOptions(this.projectState.project as Project, this.target.id);
                return {status: 'ok', res: options};
            } catch (err: unknown) {
                return {status: 'error', err: err as Error};
            }
        },
        generatedError(): Error | null {
            return this.generated.status === 'error' ? this.generated.err : null;
        },
        generatedOptions(): IVerilogWorkerOptions | null {
            return this.generated.status === 'ok' ? this.generated.res : null;
        }
    }
});
</script>

<template>
    <div style="width: 100%">
        <code v-if="generatedError" style="color: red">{{ generatedError }}</code>

        <p style="margin-bottom: 40px">
            These options configure the waveform generation step performed by
            <a href="https://github.com/steveicarus/iverilog">ICARUS Verilog</a>. You need to have at least one
            testbench configured for this task to be available.
        </p>

        <EDATestbenchSelector :targetIndex="targetIndex" />

        <vscode-divider />

        <h2>Advanced Options</h2>

        <p style="margin-bottom: 40px">
            Advanced options should not be used unless you are familiar with the underlying tools. Modifying them may
            overwrite the basic options defined above.
        </p>

        <div style="width: 100%; display: grid; gap: 1rem">
            <EDATargetValueList
                :targetIndex="targetIndex"
                :generated="generatedOptions?.steps[0]?.arguments ?? []"
                workerId="iverilog"
                workerName="IVerilog"
                configId="arguments"
                configName="arguments"
                configNameOnePerLine
            >
                Arguments passed to IVerilog for waveform generation.
                <br /><br />
                The commands should write to a file called <code>simulator.vvp</code> in the target directory. This is
                necessary for EDAcation to invoke the correct simulation command.
            </EDATargetValueList>

            <vscode-divider />

            <EDATargetValueList
                :targetIndex="targetIndex"
                :generated="generatedOptions?.inputFiles ?? []"
                workerId="iverilog"
                workerName="IVerilog"
                configId="inputFiles"
                configName="input files"
                configNameOnePerLine
            >
                Input files for waveform generation.
                <br /><br />
                This list helps EDAcation understand which files may be ingested by IVerilog. This is necessary for some
                tool providers that do not have direct access to your workspace.
            </EDATargetValueList>

            <EDATargetValueList
                :targetIndex="targetIndex"
                :generated="generatedOptions?.outputFiles ?? []"
                workerId="iverilog"
                workerName="IVerilog"
                configId="outputFiles"
                configName="output files"
                configNameOnePerLine
            >
                Output files for waveform generation.
                <br /><br />
                This list helps EDAcation understand which files may be generated by IVerilog. This is necessary to
                correctly process task results, as well as for some tool providers that do not have direct access to
                your workspace.
            </EDATargetValueList>
        </div>
    </div>
</template>
